apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-store
spec:
  template:
    spec:
      initContainers:
        - name: transfer-file-ownership
          image: index.docker.io/sourcegraph/alpine-3.12:insiders@sha256:c60832606950181f8f981360226ec4a179c4161b1de12cee4d7c930f6df2f6bb
          command: ["sh", "-c", "chown -R 999:1000 /redis-data"]
          volumeMounts:
            - mountPath: /redis-data
              name: redis-data
          securityContext:
            runAsUser: 0
